### ISSUE TITLE
Question about automatic Proton fixes

### ISSUE THREAD

**Issue by Tiagoquix** [Open-Wine-Components/umu-protonfixes#76]
Hi there.

I would like to know a thing about the automatic fixes.
When they change launch options (such as adding something like "-nolauncher") or when they add env. variables (such as WINEDLLOVERRIDES, WINE CPU TOPOLOGY, DXVK variables etc.), do they override my current launch options, or are my launch options for that game preserved?

Thanks in advance.

**Comment by R1kaB3rN** [comment]
Yes, it's possible for a fix to override the user's environment variables or replace launch options, which is why fixes should be reviewed and why users should monitor the console log. For more details, please refer to the `set_environment` and `replace_command` function in the util file.

And besides protonfixes, [environment variables can also be overridden by proton in some cases](https://github.com/ValveSoftware/Proton/blob/proton_9.0/proton#L1205).

But if you want to use your own configuration or not use a fix for whatever reason, you can either disable protonfixes entirely by setting `PROTONFIXES_DISABLE` or by defining a local fix with the same game id at `~/.config/protonfixes/localfixes.`

**Comment by R1kaB3rN** [comment]
Whoops. Actually in the case of WINE_CPU_TOPOLOGY for proton, [it'll check if that variable has been defined first before setting it](https://github.com/ValveSoftware/Proton/blob/proton_9.0/proton#L1204). And by default protonfixes [won't override the WINE_CPU_TOPOLOGY but it has the potential to](https://github.com/Open-Wine-Components/umu-protonfixes/blob/master/util.py#L796) override the environment variable that was set.

**Comment by R1kaB3rN** [comment]
By console log, I was referring to the protonfix log statements that will be printed if you're launching from a terminal. For example:

> ProtonFixes[23532] INFO: Running protonfixes
ProtonFixes[23532] INFO: Running checks
ProtonFixes[23532] INFO: All checks successful
ProtonFixes[23532] INFO: Using global defaults for UNKNOWN (1829980)
ProtonFixes[23532] INFO: Using global protonfix for UNKNOWN (1829980)
ProtonFixes[23532] INFO: Checking if winetricks quartz is installed
ProtonFixes[23532] INFO: Checking if winetricks wmp11 is installed
ProtonFixes[23532] INFO: Checking if winetricks qasf is installed

Launching games that way should be the only way to monitor the fixes that are being applied in real time. However, if you're not launching from a terminal but are interested in knowing the fixes that were applied, it'll depend on the launcher client you use. For example with the Steam client, you'll need to set `PROTON_LOG=1` which will write a log file containing the statements to your home directory.
