### ISSUE TITLE
Add UPlay fix to all UPlay-enabled titles

### ISSUE THREAD

**Issue by Tiagoquix** [Open-Wine-Components/umu-protonfixes#90]
This is the list of all games that could benefit from the UPlay overlay disable function:

https://steamdb.info/tech/Launcher/Ubisoft/

Would be nice to include all of the games here with the function.

**Comment by R1kaB3rN** [comment]
For this to scale, there would need to be a public API that will list all current games with Ubisoft launchers. Otherwise, we would need to do with what Valve does and manually add IDs in the program which I am opposed to doing. If we can find an endpoint that will list them, then perhaps we can autogenerate fixes for those games that will disable the overlay.

**Comment by R1kaB3rN** [comment]
I won't stop you from doing that, but I would just let users create a fix for them if they really want it. Also, the creators of steamdb to provide us API access won't work because the [creators encourage users to acquire Steam data directly from Steam or to use SteamKit](https://steamdb.info/faq/#how-are-we-getting-this-information).

Besides Steam there are other stores to consider as well that may provide access to this metadata from their API (e.g., GOG).

**Comment by R1kaB3rN** [comment]
Closing. See https://github.com/Open-Wine-Components/umu-protonfixes/pull/94#issuecomment-2282246528 for rationale.

Feel free to reopen if you disagree or if you know of a way to both precisely and reliably determine at runtime whether the loss of functionality as a result of disabling the overlay would cause or not cause any issues.
